apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: {{name}}
  name: {{name}}
  namespace: {{namespace}}
spec:
  replicas: 1
  selector:
    name: {{name}}
  template:
    metadata:
      labels:
        name: {{name}}
    spec:
      hostNetwork: true
      containers:
      - name: {{name}}
        image: {{docker_server}}/{{image}}
        volumeMounts:
        - name: {{name}}
          mountPath: {{volume_mount_path}}
        - name: {{name}}-secret-volume
          readOnly: true
          mountPath: /opt/secrets/{{name}}
      volumes:
      - name: {{name}}
        hostPath:
          path: {{volume_host_path}}
      - name: {{name}}-secret-volume
        secret:
          secretName: {{name}}-secret
      imagePullSecrets:
      - name: {{registry_secret}}
